server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/vueadmin?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: root
#  security:
#    user:
#      name: user
#      password: 123456

mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml

yppah:
  jwt:
    header: Authorization
    expire: 604800 #7天，秒单位
    secret: ji8n3439w4h9n43ld9ne9343fdfer49f #32位随机数即可


